config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "tasks#index"
  resources :tasks
  post "tasks/:id/toggle", to: "tasks#toggle"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true

  scope :recent,    -> { order(created_at: :desc) }
  scope :completed, -> { where(completed: true).recent }
  scope :todo,      -> { where(completed: false).recent }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.order(created_at: :desc)
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        @task.broadcast_render_to :stream_tasks, partial: 'tasks/create', locals: { task: @task }
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # # no longer needed here
  # #
  # def toggle
  #   @task = Task.find(params[:id])
  #   @task.update(completed: params[:completed])
  #   render json: { message: "Success" }
  # end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        # format.turbo_stream
        @task.broadcast_render_to :stream_tasks, partial: 'tasks/update', locals: { task: @task }
        format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      @task.broadcast_render_to :stream_tasks, partial: 'tasks/destroy', locals: { task: @task }
      format.html { redirect_to tasks_url, notice: "Post was successfully deleted." }
    end
  end

  private

  def task_params
    params.require(:task).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Mycars
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags


  body
    .mx-auto.my-5.max-w-xl(class="w-3/4" id="main-body")
      = yield

app/views/tasks/_create.turbo_stream.erb
<%= turbo_stream.prepend 'tasks' do %>
  <%= render 'tasks/task', task: task %>
<% end %>

<%= turbo_stream.replace 'new_task_form' do %>
  <%= render 'tasks/form', task: Task.new %>
<% end %>

app/views/tasks/_destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(task)) do %>
  <%= render 'tasks/task', task: task %>
<% end %>

app/views/tasks/_flash.html.slim
p.mt-4.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block(id="notice")
  = notice

app/views/tasks/_form.html.slim
= form_with(model: task, class: "", html: {id: 'new_task_form'}) do |form|
  = form.text_field :description, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none"
  = form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white"

app/views/tasks/_task.html.slim
turbo-frame.block(id=dom_id(task) data-controller="task")
  = form_with(model: task, class:"text-lg inline-block my-3 w-72") do |form|
    = form.check_box :completed, data: { id: task.id, action: "task#toggle", task_target: 'checkbox' }, class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500"

    span(class=(task.completed? ? 'line-through' : ''))
      = task.description

  = link_to "Edit", edit_task_path(task), class: "btn bg-gray-100"

  .inline-block.ml-2
    = button_to "Delete", task_path(task), method: :delete, class: "btn bg-red-100"

app/views/tasks/_update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(task)) do %>
  <%= render 'tasks/task', task: task %>
<% end %>

app/views/tasks/edit.html.erb
<div class="">
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <turbo-frame id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </turbo-frame>
</div>

app/views/tasks/index.html.slim
- if notice.present?
  = render 'flash'

= turbo_stream_from :stream_tasks

h2.font-bold.text-2xl.mb-2
  | Task Manager

.px-4.py-6.rounded.shadow
  .px-5.mb-2
    = render "form", task: @task

  #tasks.px-5
    = render @tasks

  hr

  #completed-tasks